[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'map <C-n> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'vim-airline/vim-airline'
on_i = 1
hook_add = '''
set laststatus=2
let g:airline#extensions#branch#enable=1
let g:airline#extensions#tableline#enable=1
let g:airline#extensions#wordcount#enable=0
let g:airline#extensions#default#layout=[['a','b','c'],['x','y','z']]
let g:airline_section_c='%t'
let g:airline_section_x='%{&filetype}'
"let g:airline_section_z='%31:%2v %{airline#extensions#ale#get_warning()} %{airline#extensions#ale#get_error()}'
"let g:airline#extensions#ale#error_symbol=' '
let g:airline#extensions#ale#warnign_symbol=' '
let g:airline#extensions#default#section_truncate_width={}
let g:airline#extensions#whitespace#enabled=1
'''

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = "ryanoasis/vim-devicons"

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
hook_add = '''
call ddc#custom#patch_global('sources', ['around', 'ale', 'vim-lsp', 'file'])
call ddc#custom#patch_global('sourceOptions', {
      \ 'around': {'mark': 'A'},
      \ 'ale': {'cleanResultsWhitespace': v:false},
      \ 'vim-lsp': {
      \   'mark': 'lsp',
      \   'matchers': ['matcher_head'],
      \   'sorters': ['sorter_rank'],
      \},
      \ 'file': {
      \   'mark': 'F',
      \   'isVolatile': v:true,
      \   'forceCompletionPattern': '\S/\S*',
      \},
      \ '_': {
      \   'matchers': ['matcher_head'],
      \   'sorters': ['sorter_rank'],
      \},
      \})
call ddc#enable()

inoremap <silent><expr> <TAB>
     \ pumvisible() ? '<C-n>' :
     \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
     \ '<TAB>' : ddc#manual_complete()
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
'''

[[plugins]]
repo = 'statiolake/ddc-ale'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
 repo = 'Shougo/ddc-matcher_head'
 on_source = 'ddc.vim'

[[plugins]]
 repo = 'Shougo/ddc-sorter_rank'
 on_source = 'ddc.vim'

[[plugins]]
 repo = 'shun/ddc-vim-lsp'
 on_source = 'ddc.vim'

[[plugins]]
 repo = 'LumaKernel/ddc-file'
 on_source = 'ddc.vim'
